### ISSUE TITLE
R-GAT  数据处理问题

### ISSUE THREAD

**Issue by BD-MF** [ROGERDJQ/RoBERTaABSA#7]
在使用 allennlp.predictors.predictor.Predictor 时出现以下报错信息：allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder." 请问这个问题您遇到过吗？ 或者有啥建议避坑么

使用的是：biaffine-dependency-parser-ptb-2018.08.23.tar.gz，跑您代码中的 data_preprocess_semeval.py 也报同样的错误

**Comment by BD-MF** [comment]
allennlp 等版本 是多少呢？

**Comment by ROGERDJQ** [comment]
这个问题我没有出现过，但是可能是和allen的版本有关。您在哪里使用了allennlp.predictors.predictor.Predictor呢？

**Comment by XuMayi** [comment]
请问您使用的allennlp的版本是多少，可以告知一下么，我这边也出现了类似错误。

**Comment by raaedahmed23** [comment]
Any update on this? I'm getting the same error on a different script. Using allennlp==1.0.0

**Comment by ROGERDJQ** [comment]
I am wondering which part you guys get this issue from? is the RGAT code?

**Comment by ROGERDJQ** [comment]
抱歉回复较迟。根据描述，这条issue的问题大致是在```data_preprocess_semeval.py``` and ```data_preprocess_twitter.py```这两个文件内出现的。事实上，我们在我们的实验中并没有使用这两个代码。之所以保留在代码库中主要是由于这是从原本的RGAT repo clone得到的。我们尽可能保留了原来的代码结构。如果是想得到我们文章的结果，请按照readme描述进行。我已经删去了这两个文件以免发生误操作。
Sorry for the late reply. I was kind of confused the first time. Yet now I figure out what part this issue comes from.  This error happened in ```data_preprocess_semeval.py``` and ```data_preprocess_twitter.py``` as you mentioned. These codes are from the RGAT repo and  I made few necessary changes to adapt to our experiments. With the changed code, I do not run these two files actually. Thus, you do not have to run these two files either. If you  want to get the experiment results of our work, please follow the readme.  I have already remove these two files.

**Comment by cekkay** [comment]
https://storage.googleapis.com/allennlp-public-models/biaffine-dependency-parser-ptb-2020.04.06.tar.gz
上面的版本可以成功解析，但是解析结果会有不同

**Comment by annovice** [comment]
我打不开https://storage.googleapis.com/allennlp-public-models/biaffine-dependency-parser-ptb-2020.04.06.tar.gz这个个网址
